on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     -  name: Checkout code
        uses: actions/checkout@v2
       
     -  name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
     -  name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/air-alerts-sse-listener:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install ssh client
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
          
      - name: Copy SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          
      - name: Deploy Docker image to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_INSTANCE_HOST }}
          docker stop air-alerts-sse-listener || true
          docker rm air-alerts-sse-listener || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/air-alerts-sse-listener:latest
          docker run -d --name air-alerts-sse-listener -e PORT=${{ secrets.APP_PORT }} -e DATABASE_URL=${{ secrets.APP_DATABASE_URL }} -e AIR_ALERT_API_URL=${{ secrets.APP_AIR_ALERT_API_URL }} -e AIR_ALERT_API_ACCESS_KEY=${{ secrets.APP_AIR_ALERT_API_ACCESS_KEY }} -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/air-alerts-sse-listener:latest
